const DEFAULT_MODELS: &[(&str, &str)] = &[("default", "Default (CLI config)")];
const CODEX_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("gpt-5.6-sol", "gpt-5.6-sol"),
    ("gpt-5.4", "gpt-5.4"),
    ("gpt-5.3-codex", "gpt-5.3-codex"),
    ("gpt-5.1", "gpt-5.1"),
    ("gpt-5", "gpt-5"),
];
const CODEX_REASONING: &[(&str, &str)] = &[
    ("default", "Default"),
    ("low", "Low"),
    ("medium", "Medium"),
    ("high", "High"),
    ("xhigh", "Extra high"),
];
const CLAUDE_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("sonnet", "Sonnet (alias)"),
    ("opus", "Opus (alias)"),
    ("haiku", "Haiku (alias)"),
];
const CLAUDE_REASONING: &[(&str, &str)] = &[
    ("default", "Default"),
    ("low", "Low"),
    ("medium", "Medium"),
    ("high", "High"),
    ("max", "Max"),
];
const OPENCODE_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("anthropic/claude-sonnet-4-6", "anthropic/claude-sonnet-4-6"),
    ("openai/gpt-5.4", "openai/gpt-5.4"),
    ("google/gemini-3-pro", "google/gemini-3-pro"),
];
const GEMINI_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("gemini-3-pro-preview", "gemini-3-pro-preview"),
    ("gemini-3-flash-preview", "gemini-3-flash-preview"),
    ("gemini-2.5-pro", "gemini-2.5-pro"),
    ("gemini-2.5-flash", "gemini-2.5-flash"),
];
const COPILOT_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("claude-sonnet-4.6", "Claude Sonnet 4.6"),
    ("gpt-5.2", "GPT-5.2"),
];
const CURSOR_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("auto", "Auto"),
    ("sonnet-4", "sonnet-4"),
    ("gpt-5", "gpt-5"),
];
const QWEN_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("qwen3-coder-plus", "qwen3-coder-plus"),
    ("qwen3-coder-flash", "qwen3-coder-flash"),
];
const KIMI_FALLBACK_MODELS: &[(&str, &str)] = &[
    ("default", "Default (CLI config)"),
    ("kimi-code/kimi-for-coding", "kimi-code/kimi-for-coding"),
    ("kimi-k2-turbo-preview", "kimi-k2-turbo-preview"),
    ("moonshot-v1-8k", "moonshot-v1-8k"),
    ("moonshot-v1-32k", "moonshot-v1-32k"),
];

const LOCAL_CLI_DEFINITIONS: &[LocalCliDefinition] = &[
    LocalCliDefinition {
        id: "codex",
        name: "Codex CLI",
        bin: "codex",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &["login", "status"],
        fallback_models: CODEX_FALLBACK_MODELS,
        reasoning_options: CODEX_REASONING,
        probe_models: probe_codex_models,
        smoke_invocation: codex_smoke_invocation,
        task_command: codex_task_command,
    },
    LocalCliDefinition {
        id: "hermes",
        name: "Hermes",
        bin: "hermes",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &["config", "check"],
        fallback_models: DEFAULT_MODELS,
        reasoning_options: &[],
        probe_models: probe_hermes_models,
        smoke_invocation: hermes_smoke_invocation,
        task_command: hermes_task_command,
    },
    LocalCliDefinition {
        id: "claude",
        name: "Claude Code",
        bin: "claude",
        fallback_bins: &["openclaude"],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &["auth", "status"],
        fallback_models: CLAUDE_FALLBACK_MODELS,
        reasoning_options: CLAUDE_REASONING,
        probe_models: probe_no_models,
        smoke_invocation: claude_smoke_invocation,
        task_command: claude_task_command,
    },
    LocalCliDefinition {
        id: "opencode",
        name: "OpenCode",
        bin: "opencode",
        fallback_bins: &["opencode-cli"],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &[],
        fallback_models: OPENCODE_FALLBACK_MODELS,
        reasoning_options: &[],
        probe_models: probe_opencode_models,
        smoke_invocation: opencode_smoke_invocation,
        task_command: opencode_task_command,
    },
    LocalCliDefinition {
        id: "gemini",
        name: "Gemini CLI",
        bin: "gemini",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &[],
        fallback_models: GEMINI_FALLBACK_MODELS,
        reasoning_options: &[],
        probe_models: probe_no_models,
        smoke_invocation: gemini_smoke_invocation,
        task_command: gemini_task_command,
    },
    LocalCliDefinition {
        id: "copilot",
        name: "GitHub Copilot CLI",
        bin: "copilot",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &[],
        fallback_models: COPILOT_FALLBACK_MODELS,
        reasoning_options: &[],
        probe_models: probe_no_models,
        smoke_invocation: copilot_smoke_invocation,
        task_command: copilot_task_command,
    },
    LocalCliDefinition {
        id: "cursor-agent",
        name: "Cursor Agent",
        bin: "cursor-agent",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &["status"],
        fallback_models: CURSOR_FALLBACK_MODELS,
        reasoning_options: &[],
        probe_models: probe_cursor_models,
        smoke_invocation: cursor_smoke_invocation,
        task_command: cursor_task_command,
    },
    LocalCliDefinition {
        id: "qwen",
        name: "Qwen Code",
        bin: "qwen",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &[],
        fallback_models: QWEN_FALLBACK_MODELS,
        reasoning_options: &[],
        probe_models: probe_no_models,
        smoke_invocation: qwen_smoke_invocation,
        task_command: qwen_task_command,
    },
    LocalCliDefinition {
        id: "kimi",
        name: "Kimi Code",
        bin: "kimi",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &[],
        fallback_models: KIMI_FALLBACK_MODELS,
        reasoning_options: &[],
        probe_models: probe_no_models,
        smoke_invocation: kimi_smoke_invocation,
        task_command: kimi_task_command,
    },
    LocalCliDefinition {
        id: "kilo",
        name: "Kilo Code",
        bin: "kilo",
        fallback_bins: &[],
        adapter_version: 1,
        version_args: &["--version"],
        auth_args: &[],
        fallback_models: DEFAULT_MODELS,
        reasoning_options: &[],
        probe_models: probe_kilo_models,
        smoke_invocation: kilo_smoke_invocation,
        task_command: kilo_task_command,
    },
];
